/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/all-collections`; params?: Router.UnknownInputParams; } | { pathname: `/all-tasks`; params?: Router.UnknownInputParams; } | { pathname: `/detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/capture` | `/capture`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pending` | `/pending`; params?: Router.UnknownInputParams; } | { pathname: `/collection/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/all-collections`; params?: Router.UnknownOutputParams; } | { pathname: `/all-tasks`; params?: Router.UnknownOutputParams; } | { pathname: `/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/capture` | `/capture`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/pending` | `/pending`; params?: Router.UnknownOutputParams; } | { pathname: `/collection/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/all-collections${`?${string}` | `#${string}` | ''}` | `/all-tasks${`?${string}` | `#${string}` | ''}` | `/detail${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/capture${`?${string}` | `#${string}` | ''}` | `/capture${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/pending${`?${string}` | `#${string}` | ''}` | `/pending${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/all-collections`; params?: Router.UnknownInputParams; } | { pathname: `/all-tasks`; params?: Router.UnknownInputParams; } | { pathname: `/detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/capture` | `/capture`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/pending` | `/pending`; params?: Router.UnknownInputParams; } | `/collection/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/collection/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
